default_workers: auto
default_dist_scope: "loadscope"
 
report:
  unified_report_path: ./reports//test_results.html   # unified report output
  batch_report_folder: ./reports//batch_reports  # folder to save individual test results
 
folders:
  test_daily_batch:
      workers: "auto"
      dist_scope: "loadfile"
      testfiles:
        - "SRC/tests/tests_ui"
        - "SRC/tests/tests_api"
  test_home:
      workers: "auto"
      dist_scope: "loadfile"
      testfiles:
        - "SRC/tests/tests_ui/test_homepage.py"
        - "SRC/tests/tests_ui/test_order.py"
  test_weekly_batch:
      workers: "auto"
      testfiles:
        - "SRC/tests/tests_ui/test_login.py"
        - "SRC/tests/tests_ui/test_homepage.py"
        - "SRC/tests/tests_api/test_bookers_api.py"